version: '3.8'
services:
  app:
    # Construction de l'image à partir du Dockerfile local
    build: .
    # Mapping du port 8080 de l'ordinateur vers le port 80 du conteneur
    ports:
      - "8080:80"
    # Montage de volume pour voir les modifs de code en temps réel
    volumes:
      - .:/var/www/html