version: '3.8'

services:
  portfolio-app:
    build: .
    container_name: portfolio_container
    ports:
      - "8080:80" 
    volumes:
      - .:/var/www/html 
    networks:
      - portfolio-network
networks:
  portfolio-network:
    driver: bridge